-- Customer portal successful-login audit log.
-- Run once in the Supabase SQL Editor before deploying the matching site files.
create table if not exists public.customer_login_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  project_id uuid references public.projects(id) on delete set null,
  username text not null,
  project_name text,
  logged_in_at timestamptz not null default now(),
  ip_address inet,
  user_agent text
);

create index if not exists customer_login_log_logged_in_at_idx
  on public.customer_login_log (logged_in_at desc);
create index if not exists customer_login_log_user_id_idx
  on public.customer_login_log (user_id);

alter table public.customer_login_log enable row level security;

-- Browser clients cannot read or write audit records. The Netlify function
-- validates the signed-in user and uses the service role for both operations.
revoke all on public.customer_login_log from anon, authenticated;
