const cfg=window.ADELIE_PORTAL_CONFIG,sb=supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey),$=id=>document.getElementById(id);let projects=[];function show(t,type='success'){const m=$('admin-message');m.textContent=t;m.className='notice '+type;scrollTo({top:0,behavior:'smooth'})}async function guard(){const {data:{session}}=await sb.auth.getSession();if(!session)return location.href='portal-login.html';const {data:isAdmin}=await sb.rpc('is_portal_admin');if(!isAdmin)return location.href='portal.html';loadProjects()}function values(ids){return Object.fromEntries(ids.map(id=>[id,$(id).value||null]))}async function insert(table,payload,msg,form){const {error}=await sb.from(table).insert(payload);if(error)return show(error.message,'error');form?.reset();show(msg)}async function loadProjects(){const {data,error}=await sb.from('projects').select('*').order('created_at',{ascending:false});if(error)return show(error.message,'error');projects=data||[];$('projects-list').innerHTML=projects.length?'<table class="portal-table"><thead><tr><th>Project</th><th>Phase</th><th>Progress</th><th>Status</th></tr></thead><tbody>'+projects.map(p=>`<tr><td><strong>${p.name}</strong><br><span class="portal-muted">${p.address}</span></td><td>${p.current_phase}</td><td>${p.progress_percent||0}%</td><td>${p.status}</td></tr>`).join('')+'</tbody></table>':'<div class="empty">No projects yet.</div>';const opts=projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');document.querySelectorAll('.project-select').forEach(s=>s.innerHTML=opts)}
$('project-form').onsubmit=async e=>{e.preventDefault();await insert('projects',{name:$('new-project-name').value,address:$('new-project-address').value,current_phase:$('new-project-phase').value,start_date:$('new-start').value||null,target_completion_date:$('new-end').value||null,status:'Active',progress_percent:0},'Project created.',e.target);loadProjects()};
$('invite-form').onsubmit=async e=>{e.preventDefault();const {data:{session}}=await sb.auth.getSession();const r=await fetch('/.netlify/functions/invite-client',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({email:$('invite-email').value.trim(),projectId:$('invite-project').value,redirectTo:location.origin+'/portal-login.html'})});const out=await r.json();show(out.message||out.error,r.ok?'success':'error')};
$('daily-log-form').onsubmit=e=>{e.preventDefault();insert('daily_logs',{project_id:$('daily-project').value,log_date:$('daily-date').value,title:$('daily-title').value,work_completed:$('daily-work').value,delays_or_issues:$('daily-issues').value,next_steps:$('daily-next').value,visible_to_client:$('daily-visible').checked},'Daily log posted.',e.target)};
$('task-form').onsubmit=e=>{e.preventDefault();insert('project_tasks',{project_id:$('task-project').value,title:$('task-title').value,description:$('task-description').value,due_date:$('task-due').value||null,status:$('task-status').value,visible_to_client:$('task-visible').checked},'Task added.',e.target)};
$('selection-form').onsubmit=e=>{e.preventDefault();insert('material_selections',{project_id:$('selection-project').value,category:$('selection-category').value,item_name:$('selection-item').value,manufacturer:$('selection-manufacturer').value,model_or_color:$('selection-model').value,decision_due_date:$('selection-due').value||null,status:$('selection-status').value,notes:$('selection-notes').value},'Selection added.',e.target)};
$('permit-form').onsubmit=e=>{e.preventDefault();insert('permits',{project_id:$('permit-project').value,permit_type:$('permit-type').value,permit_number:$('permit-number').value,jurisdiction:$('permit-jurisdiction').value,status:$('permit-status').value},'Permit added.',e.target)};
$('inspection-form').onsubmit=e=>{e.preventDefault();insert('inspections',{project_id:$('inspection-project').value,inspection_type:$('inspection-type').value,scheduled_date:$('inspection-date').value||null,inspector_or_agency:$('inspection-agency').value,result:$('inspection-result').value,notes:$('inspection-notes').value},'Inspection added.',e.target)};
$('invoice-form').onsubmit=e=>{e.preventDefault();insert('invoices',{project_id:$('invoice-project').value,invoice_number:$('invoice-number').value,amount:Number($('invoice-amount').value),issued_date:$('invoice-issued').value||null,due_date:$('invoice-due').value||null,status:$('invoice-status').value},'Invoice added.',e.target)};
$('payment-form').onsubmit=e=>{e.preventDefault();insert('payments',{project_id:$('payment-project').value,amount:Number($('payment-amount').value),payment_date:$('payment-date').value||null,payment_method:$('payment-method').value,reference_number:$('payment-reference').value},'Payment recorded.',e.target)};
$('document-form').onsubmit=async e=>{e.preventDefault();const f=$('document-file').files[0],pid=$('document-project').value,path=`${pid}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;let {error}=await sb.storage.from('project-files').upload(path,f);if(error)return show(error.message,'error');({error}=await sb.from('documents').insert({project_id:pid,title:$('document-title').value,category:$('document-category').value,bucket:'project-files',storage_path:path,file_name:f.name}));if(error)return show(error.message,'error');e.target.reset();show('Document uploaded securely.')};
$('photo-form').onsubmit=async e=>{e.preventDefault();const f=$('photo-file').files[0],pid=$('photo-project').value,path=`${pid}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;let {error}=await sb.storage.from('project-photos').upload(path,f);if(error)return show(error.message,'error');({error}=await sb.from('project_photos').insert({project_id:pid,caption:$('photo-caption').value,bucket:'project-photos',storage_path:path,taken_at:new Date().toISOString()}));if(error)return show(error.message,'error');e.target.reset();show('Photo uploaded securely.')};
$('admin-message-form').onsubmit=async e=>{e.preventDefault();const {data:{user}}=await sb.auth.getUser();await insert('messages',{project_id:$('message-project').value,sender_id:user.id,sender_role:'admin',body:$('admin-message-body').value},'Client update posted.',e.target)};$('logout').onclick=async()=>{await sb.auth.signOut();location.href='portal-login.html'};guard();