const cfg=window.ADELIE_PORTAL_CONFIG,sb=supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);let projectId=null;const el=id=>document.getElementById(id),fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—',money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0)),safe=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const empty=t=>`<div class="empty">${t}</div>`,list=rows=>`<ul class="portal-list">${rows.join('')}</ul>`;
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session)return location.href='portal-login.html';el('user-email').textContent=session.user.email;const {data:isAdmin}=await sb.rpc('is_portal_admin');if(isAdmin)return location.href='portal-admin.html';const {data:members,error}=await sb.from('project_members').select('project_id,projects(*)').eq('user_id',session.user.id).limit(1);if(error||!members?.length){el('loading').innerHTML='<div class="empty"><h2>No project is connected yet.</h2><p>Your account is active, but ADELIE has not assigned a project. Contact hello@adelieconstruction.com.</p></div>';return}const p=members[0].projects;projectId=p.id;el('project-name').textContent=p.name;el('project-address').textContent=p.address;el('project-status').textContent=p.status;el('current-phase').textContent=p.current_phase;el('start-date').textContent=fmt(p.start_date);el('completion-date').textContent=fmt(p.target_completion_date);el('progress-bar').style.width=(p.progress_percent||0)+'%';el('progress-label').textContent=(p.progress_percent||0)+'% complete';await Promise.all([loadMilestones(),loadDailyLogs(),loadTasks(),loadPermits(),loadInspections(),loadSelections(),loadDocuments(),loadPhotos(),loadInvoices(),loadChanges(),loadPayments(),loadMessages(),loadWarranty()]);el('loading').classList.add('hidden');el('app').classList.remove('hidden')}
async function q(table,order='created_at',ascending=false){const {data=[],error}=await sb.from(table).select('*').eq('project_id',projectId).order(order,{ascending});return error?[]:data}
async function loadMilestones(){const data=await q('milestones','sort_order',true);el('milestones').innerHTML=data.length?'<table class="portal-table"><thead><tr><th>Milestone</th><th>Target</th><th>Status</th></tr></thead><tbody>'+data.map(x=>`<tr><td><strong>${safe(x.title)}</strong><br><span class="portal-muted">${safe(x.description)}</span></td><td>${fmt(x.target_date)}</td><td><span class="status-pill">${safe(x.status)}</span></td></tr>`).join('')+'</tbody></table>':empty('No milestones posted yet.')}
async function loadDailyLogs(){const data=await q('daily_logs','log_date',false);el('daily-logs-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${fmt(x.log_date)} — ${safe(x.title)}</strong>${x.work_completed?`<p>${safe(x.work_completed)}</p>`:''}${x.delays_or_issues?`<p><b>Delays or issues:</b> ${safe(x.delays_or_issues)}</p>`:''}${x.next_steps?`<p class="portal-muted"><b>Next:</b> ${safe(x.next_steps)}</p>`:''}</li>`)):empty('No daily updates have been posted.')}
async function loadTasks(){const data=await q('project_tasks','sort_order',true);el('tasks-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${safe(x.title)}</strong><br><span class="status-pill">${safe(x.status)}</span> <span class="portal-muted">Due ${fmt(x.due_date)}</span>${x.description?`<p>${safe(x.description)}</p>`:''}</li>`)):empty('No customer-visible tasks posted.')}
async function loadPermits(){const data=await q('permits','created_at',false);el('permits-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${safe(x.permit_type)}</strong><br><span class="status-pill">${safe(x.status)}</span>${x.permit_number?` · ${safe(x.permit_number)}`:''}<br><span class="portal-muted">${safe(x.jurisdiction)}</span></li>`)):empty('No permit records posted.')}
async function loadInspections(){const data=await q('inspections','scheduled_date',true);el('inspections-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${safe(x.inspection_type)}</strong><br>${fmt(x.scheduled_date)} · <span class="status-pill">${safe(x.result)}</span>${x.notes?`<p class="portal-muted">${safe(x.notes)}</p>`:''}</li>`)):empty('No inspections posted.')}
async function loadSelections(){const data=await q('material_selections','decision_due_date',true);el('selections-list').innerHTML=data.length?'<table class="portal-table"><thead><tr><th>Category</th><th>Selection</th><th>Due</th><th>Status</th></tr></thead><tbody>'+data.map(x=>`<tr><td>${safe(x.category)}</td><td><strong>${safe(x.item_name)}</strong><br><span class="portal-muted">${safe([x.manufacturer,x.model_or_color].filter(Boolean).join(' · '))}</span></td><td>${fmt(x.decision_due_date)}</td><td><span class="status-pill">${safe(x.status)}</span></td></tr>`).join('')+'</tbody></table>':empty('No selections posted.')}
async function signed(bucket,path){if(!path)return null;if(path.startsWith('http')||path.startsWith('assets/'))return path;const {data}=await sb.storage.from(bucket).createSignedUrl(path,3600);return data?.signedUrl}
async function loadDocuments(){const data=await q('documents');const rows=await Promise.all(data.map(async x=>({...x,url:await signed(x.bucket||'project-files',x.storage_path)})));el('documents-list').innerHTML=rows.length?list(rows.map(x=>`<li><strong>${safe(x.title)}</strong> <span class="portal-muted">${safe(x.category)}</span><br>${x.url?`<a href="${x.url}" target="_blank" rel="noopener">Open document</a>`:'File not available'}</li>`)):empty('No project documents posted yet.')}
async function loadPhotos(){const data=await q('project_photos','taken_at',false);const rows=await Promise.all(data.map(async x=>({...x,url:await signed(x.bucket||'project-photos',x.storage_path)})));el('photos-list').innerHTML=rows.length?'<div class="photo-grid">'+rows.map(x=>`<figure>${x.url?`<img src="${x.url}" alt="${safe(x.caption||'Project photo')}">`:''}<figcaption>${safe(x.caption)}</figcaption></figure>`).join('')+'</div>':empty('No photos posted yet.')}
async function loadInvoices(){const data=await q('invoices','issued_date',false);el('invoices-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${safe(x.invoice_number)}</strong> — ${money(x.amount)}<br><span class="portal-muted">Issued ${fmt(x.issued_date)} · ${safe(x.status)}</span></li>`)):empty('No invoices posted.')}
async function loadChanges(){const data=await q('change_orders');el('change-orders-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${safe(x.change_order_number)}: ${safe(x.title)}</strong><br>${money(x.amount)} · <span class="status-pill">${safe(x.status)}</span></li>`)):empty('No change orders posted.')}
async function loadPayments(){const data=await q('payments','payment_date',false);el('payments-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${money(x.amount)}</strong><br><span class="portal-muted">${fmt(x.payment_date)} · ${safe(x.payment_method||x.status)}</span></li>`)):empty('No payments recorded.')}
async function loadMessages(){const data=await q('messages');el('messages-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${x.sender_role==='admin'?'ADELIE Construction':'You'}</strong> <span class="portal-muted">${new Date(x.created_at).toLocaleString()}</span><p>${safe(x.body)}</p></li>`)):empty('No messages yet.')}
async function loadWarranty(){const data=await q('warranty_items','end_date',true);el('warranty-list').innerHTML=data.length?list(data.map(x=>`<li><strong>${safe(x.title)}</strong><br><span class="status-pill">${safe(x.status)}</span> <span class="portal-muted">${fmt(x.start_date)}–${fmt(x.end_date)}</span>${x.description?`<p>${safe(x.description)}</p>`:''}</li>`)):empty('Warranty information and closeout records will appear here as your project reaches completion.')}
el('message-form').addEventListener('submit',async e=>{e.preventDefault();const body=el('message-body').value.trim();if(!body)return;const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from('messages').insert({project_id:projectId,sender_id:user.id,sender_role:'client',body});if(!error){el('message-body').value='';loadMessages()}});el('logout').onclick=async()=>{await sb.auth.signOut();location.href='portal-login.html'};init();